version: 2
jobs:
  build:
    machine:
      enabled: true
      image: circleci/classic:201708-01
    
    branches:
      ignore:
        - ignorebranchnamehere

    steps:
      - checkout

      - run:
          echo "hello world"
