version: 2
jobs:
  build:
    docker:
      - image: 192266199578.dkr.ecr.us-east-2.amazonaws.com/testcircleci:latest
        aws_auth:
          aws_access_key_id: $AWS_ACCESS_KEY_ID
          aws_secret_access_key: $AWS_SECRET_ACCESS_KEY
    
    steps:
      - checkout

      - run:
          echo "hello world"

      
workflows:
  version: 2
  build-deploy:
    jobs:
      - build
